# Generated by Django 5.2.1 on 2025-05-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
